name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Set Cloudflare Secrets
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          echo "Setting Cloudflare secrets..."
          npx wrangler secret put SUPABASE_URL <<< "${{ secrets.SUPABASE_URL }}"
          npx wrangler secret put SUPABASE_ANON_KEY <<< "${{ secrets.SUPABASE_ANON_KEY }}"
          npx wrangler secret put OPENROUTER_API_KEY <<< "${{ secrets.OPENROUTER_API_KEY }}"
          npx wrangler secret put WORKER_URL <<< "${{ secrets.WORKER_URL }}"

      - name: Build
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        run: npm run build

      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npm run deploy

      - name: Deployment Status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful!"
            echo "Worker URL: ${{ secrets.WORKER_URL }}"
          else
            echo "❌ Deployment failed"
            exit 1
          fi